### PR TITLE
Show teams

### PR DESCRIPTION
**Pull request by boboquack**
Mobile users can't easily see pins, and anyway I'm not 100% sure that they work.

### CODE REVIEW

**Comment by ffao** [comment]
This would cause the current teams to be unpinned... I'm also not fully convinced that this is easier than opening up the starboard to look.

**Comment by boboquack** [comment]
Sorry, why would this cause current teams to be unpinned?

**Comment by Tumbler** [comment]
Shiro pins any messages she posts that look like team messages. There is apparently a max pin limit per day or something, so this would make Shiro run out of pins really fast.

**Comment by ffao** [comment]
Yes, what Tumbler said is correct.

**Comment by boboquack** [comment]
(not sure if you all got a notification, but I fixed the pinning problem)

**Pull request merged**
